# Generated by Django 5.2.10 on 2026-01-25 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_remove_userchallenge_ai_challenge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='coaching',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='source',
            field=models.CharField(choices=[('DUDUK', '두둑 챌린지'), ('EVENT', '이벤트 챌린지'), ('USER', '사용자 챌린지')], default='DUDUK', max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
