# Generated by Django 5.2.10 on 2026-01-26 08:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_remove_challenge_coaching_alter_challenge_source_and_more'),
        ('coaching', '0004_coaching_estimated_savings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='챌린지 이름')),
                ('description', models.TextField(verbose_name='상세 설명')),
                ('icon', models.CharField(blank=True, default='target', max_length=50, verbose_name='아이콘')),
                ('icon_color', models.CharField(blank=True, default='#4CAF50', max_length=20, verbose_name='아이콘 색상')),
                ('source_type', models.CharField(choices=[('duduk', '두둑 챌린지'), ('event', '이벤트 챌린지')], default='duduk', max_length=20, verbose_name='챌린지 출처')),
                ('difficulty', models.CharField(choices=[('easy', '쉬움'), ('medium', '보통'), ('hard', '어려움')], default='medium', max_length=10, verbose_name='난이도')),
                ('base_points', models.IntegerField(default=0, verbose_name='기본 포인트')),
                ('points_formula', models.CharField(blank=True, max_length=200, null=True, verbose_name='포인트 공식')),
                ('max_points', models.IntegerField(blank=True, null=True, verbose_name='최대 포인트')),
                ('has_penalty', models.BooleanField(default=False, verbose_name='패널티 여부')),
                ('penalty_formula', models.CharField(blank=True, max_length=200, null=True, verbose_name='패널티 공식')),
                ('max_penalty', models.IntegerField(blank=True, null=True, verbose_name='최대 패널티')),
                ('bonus_condition', models.JSONField(blank=True, null=True, verbose_name='보너스 조건')),
                ('bonus_points', models.IntegerField(blank=True, null=True, verbose_name='보너스 포인트')),
                ('duration_days', models.IntegerField(default=7, verbose_name='기본 기간(일)')),
                ('is_versus', models.BooleanField(default=False, verbose_name='대결 여부')),
                ('success_conditions', models.JSONField(verbose_name='성공 조건')),
                ('user_inputs', models.JSONField(blank=True, null=True, verbose_name='사용자 입력 정의')),
                ('requires_daily_check', models.BooleanField(default=False, verbose_name='일일 체크 필요')),
                ('requires_photo', models.BooleanField(default=False, verbose_name='사진 인증 필요')),
                ('photo_frequency', models.CharField(blank=True, max_length=20, null=True, verbose_name='사진 인증 빈도')),
                ('photo_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='사진 인증 설명')),
                ('success_description', models.TextField(verbose_name='성공 조건 설명')),
                ('display_config', models.JSONField(blank=True, default=dict, verbose_name='프론트 표시 설정')),
                ('event_start_at', models.DateTimeField(blank=True, null=True, verbose_name='이벤트 시작일')),
                ('event_end_at', models.DateTimeField(blank=True, null=True, verbose_name='이벤트 종료일')),
                ('event_banner_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='이벤트 배너 URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('display_order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '챌린지 템플릿',
                'verbose_name_plural': '챌린지 템플릿 목록',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeVersusMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_a_config', models.JSONField(verbose_name='사용자 A 설정')),
                ('user_b_config', models.JSONField(verbose_name='사용자 B 설정')),
                ('user_a_score', models.JSONField(blank=True, default=dict, verbose_name='사용자 A 점수')),
                ('user_b_score', models.JSONField(blank=True, default=dict, verbose_name='사용자 B 점수')),
                ('status', models.CharField(choices=[('active', '진행 중'), ('completed', '완료')], default='active', max_length=20, verbose_name='상태')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='시작일시')),
                ('ends_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='종료일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '대결 매칭',
                'verbose_name_plural': '대결 매칭 목록',
            },
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='current_spent',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='points_earned',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='target_amount',
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='attempt_number',
            field=models.IntegerField(default=1, verbose_name='시도 횟수'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='base_points',
            field=models.IntegerField(default=0, verbose_name='기본 포인트'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='bonus_condition',
            field=models.JSONField(blank=True, null=True, verbose_name='보너스 조건'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='bonus_earned',
            field=models.BooleanField(default=False, verbose_name='보너스 획득'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='bonus_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='보너스 포인트'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='상세 설명'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='difficulty',
            field=models.CharField(choices=[('easy', '쉬움'), ('medium', '보통'), ('hard', '어려움')], default='medium', max_length=10, verbose_name='난이도'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='display_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='프론트 표시 설정'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='duration_days',
            field=models.IntegerField(default=7, verbose_name='기간(일)'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='earned_points',
            field=models.IntegerField(default=0, verbose_name='획득 포인트'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='ends_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='종료일시'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='final_spent',
            field=models.IntegerField(blank=True, null=True, verbose_name='최종 지출'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='has_penalty',
            field=models.BooleanField(default=False, verbose_name='패널티 여부'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='icon',
            field=models.CharField(default='target', max_length=50, verbose_name='아이콘'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='icon_color',
            field=models.CharField(default='#4CAF50', max_length=20, verbose_name='아이콘 색상'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='is_versus',
            field=models.BooleanField(default=False, verbose_name='대결 여부'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='max_penalty',
            field=models.IntegerField(blank=True, null=True, verbose_name='최대 패널티'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='max_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='최대 포인트'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='name',
            field=models.CharField(default='챌린지', max_length=100, verbose_name='챌린지 이름'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_challenges', to=settings.AUTH_USER_MODEL, verbose_name='대결 상대'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='penalty_formula',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='패널티 공식'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='penalty_points',
            field=models.IntegerField(default=0, verbose_name='패널티 포인트'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='photo_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='사진 인증 설명'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='photo_frequency',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='사진 인증 빈도'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='points_formula',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='포인트 공식'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='previous_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='challenges.userchallenge', verbose_name='이전 시도'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='progress',
            field=models.JSONField(blank=True, default=dict, verbose_name='진행 상황'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='requires_daily_check',
            field=models.BooleanField(default=False, verbose_name='일일 체크 필요'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='requires_photo',
            field=models.BooleanField(default=False, verbose_name='사진 인증 필요'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='source_coaching',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_challenges', to='coaching.coaching', verbose_name='원본 코칭'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='source_type',
            field=models.CharField(choices=[('duduk', '두둑 챌린지'), ('event', '이벤트 챌린지'), ('custom', '사용자 커스텀'), ('ai', 'AI 맞춤')], default='duduk', max_length=20, verbose_name='챌린지 유형'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='success_conditions',
            field=models.JSONField(default=dict, verbose_name='성공 조건'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='success_description',
            field=models.TextField(blank=True, null=True, verbose_name='성공 조건 설명'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='system_generated_values',
            field=models.JSONField(blank=True, default=dict, verbose_name='시스템 생성값'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='user_input_values',
            field=models.JSONField(blank=True, default=dict, verbose_name='사용자 입력값'),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='완료일시'),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='시작일시'),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='status',
            field=models.CharField(choices=[('active', '진행 중'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소')], default='active', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.CreateModel(
            name='ChallengeDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(verbose_name='기록 날짜')),
                ('spent_amount', models.IntegerField(default=0, verbose_name='지출 금액')),
                ('transaction_count', models.IntegerField(default=0, verbose_name='거래 건수')),
                ('spent_by_category', models.JSONField(blank=True, default=dict, verbose_name='카테고리별 지출')),
                ('is_checked', models.BooleanField(default=False, verbose_name='체크 여부')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='체크 일시')),
                ('photo_urls', models.JSONField(blank=True, default=list, verbose_name='사진 URL')),
                ('condition_met', models.BooleanField(blank=True, null=True, verbose_name='조건 충족')),
                ('condition_detail', models.JSONField(blank=True, null=True, verbose_name='조건 상세')),
                ('note', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='challenges.userchallenge', verbose_name='사용자 챌린지')),
            ],
            options={
                'verbose_name': '일별 챌린지 로그',
                'verbose_name_plural': '일별 챌린지 로그 목록',
                'ordering': ['-log_date'],
            },
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_challenges', to='challenges.challengetemplate', verbose_name='템플릿'),
        ),
        migrations.AddIndex(
            model_name='userchallenge',
            index=models.Index(fields=['user', 'status'], name='challenges__user_id_407057_idx'),
        ),
        migrations.AddIndex(
            model_name='userchallenge',
            index=models.Index(fields=['ends_at'], name='challenges__ends_at_e2269f_idx'),
        ),
        migrations.AddField(
            model_name='challengeversusmatch',
            name='user_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versus_matches_as_a', to=settings.AUTH_USER_MODEL, verbose_name='사용자 A'),
        ),
        migrations.AddField(
            model_name='challengeversusmatch',
            name='user_a_challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versus_as_a', to='challenges.userchallenge', verbose_name='사용자 A 챌린지'),
        ),
        migrations.AddField(
            model_name='challengeversusmatch',
            name='user_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versus_matches_as_b', to=settings.AUTH_USER_MODEL, verbose_name='사용자 B'),
        ),
        migrations.AddField(
            model_name='challengeversusmatch',
            name='user_b_challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versus_as_b', to='challenges.userchallenge', verbose_name='사용자 B 챌린지'),
        ),
        migrations.AddField(
            model_name='challengeversusmatch',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versus_wins', to=settings.AUTH_USER_MODEL, verbose_name='승자'),
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.AlterUniqueTogether(
            name='challengedailylog',
            unique_together={('user_challenge', 'log_date')},
        ),
    ]
