# Generated by Django 5.2.10 on 2026-01-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_challengetemplate_challengeversusmatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengetemplate',
            name='is_versus',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='is_versus',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='opponent',
        ),
        migrations.DeleteModel(
            name='ChallengeVersusMatch',
        ),
    ]
