# Generated by Django 5.2.10 on 2026-02-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_alter_userchallenge_ends_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='status',
            field=models.CharField(choices=[('ready', '시작 대기'), ('active', '진행 중'), ('completed', '완료'), ('failed', '실패')], default='active', max_length=20, verbose_name='상태'),
        ),
    ]
