# Generated by Django 5.2.11 on 2026-02-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_alter_userchallenge_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengetemplate',
            name='success_description',
            field=models.JSONField(blank=True, default=list, help_text="성공 조건 리스트 (예: ['3일 연속 진행', '매일 0원 지출'])"),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='success_description',
            field=models.JSONField(blank=True, default=list, help_text='성공 조건 리스트', verbose_name='성공 조건 설명'),
        ),
    ]
