# Generated by Django 5.2.11 on 2026-02-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('COACHING', '코칭 생성'), ('MONTHLY_REPORT', '월간 리포트 생성'), ('CHALLENGE', '챌린지')], max_length=20),
        ),
    ]
