# Generated by Django 4.2.27 on 2026-01-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_character_name_user_character_type_user_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images/",
                verbose_name="프로필 이미지",
            ),
        ),
    ]
