# Generated by Django 5.2.8 on 2026-02-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_monthlyreport_report_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ai_persona_summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="월간 리포트 분석을 통해 누적된 사용자의 소비 성향 요약 데이터",
                verbose_name="AI 소비 성향 요약",
            ),
        ),
    ]
