# Generated by Django 6.0.2 on 2026-03-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_monthlyreport_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 시각'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='score_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='점수 생성 시각'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 시각'),
        ),
        migrations.AlterField(
            model_name='user',
            name='character_type',
            field=models.CharField(choices=[('char_cat', '고양이'), ('char_dog', '강아지'), ('char_ham', '햄스터'), ('char_sheep', '양')], default='char_cat', max_length=20, verbose_name='캐릭터 타입'),
        ),
    ]
