# Generated by Django 5.2.10 on 2026-01-30 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0004_coaching_estimated_savings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachingfeedback',
            options={'verbose_name': '코칭 피드백', 'verbose_name_plural': '코칭 피드백 목록'},
        ),
        migrations.AddField(
            model_name='coachingfeedback',
            name='coaching',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='coaching.coaching', verbose_name='코칭'),
        ),
    ]
