# Generated by Django 5.2.10 on 2026-03-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0005_alter_coachingfeedback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaching',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
