# Generated by Django 5.2.10 on 2026-01-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transaction_created_at'),
        ('transactions', '0007_alter_transaction_created_at_monthlylog'),
    ]

    operations = [
    ]
